title: "Farzaneh Entezari"
email: farzaneh.entezari@mail.mcgill.ca
description: >- # this means to ignore newlines until "baseurl:"
  This is my portfolio website!
baseurl: "/" 
url: "https://farzanehentezari.github.io/" 
twitter_username: 
github_username: FarzanehEntezari

sass:
  sass_dir: _sass

icon: /assets/img/icon.jpg
